/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-page-custom-font */
import { Provider } from 'jotai';
import type { Metadata } from 'next';
import { OverlayProvider } from 'overlay-kit';
import '@repo/ui/styles.css';
import './globals.css';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko">
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/fonts-archive/Paperlogy/Paperlogy.css"
          type="text/css"
        />
      </head>

      <body className="h-dvh w-full overflow-hidden p-8">
        <Provider>
          <OverlayProvider>
            <div className="relative container mx-auto flex h-full flex-col gap-x-8 overflow-hidden lg:grid lg:grid-cols-[240px_1fr] lg:grid-rows-1">
              {children}
            </div>
          </OverlayProvider>
        </Provider>
      </body>
    </html>
  );
}
