/* eslint-disable @next/next/google-font-display */
/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from 'next';
import { OverlayProvider } from 'overlay-kit';
import 'swiper/css';
import 'swiper/css/free-mode';
import 'swiper/css/grid';
import 'swiper/css/mousewheel';
import 'swiper/css/pagination';
import 'swiper/css/scrollbar';
import Nav from '@/shared/Nav';
import '@repo/ui/styles.css';
import '@repo/ui/styles.css';
import './globals.css';
import Provider from './provider';

export const metadata: Metadata = {
  title: 'Create Turborepo',
  description: 'Generated by create turbo',
};

export default function RootLayout({ children }: { children: React.ReactNode }) {
  return (
    <html lang="ko" suppressHydrationWarning>
      <head>
        <link
          rel="stylesheet"
          href="https://fonts.googleapis.com/css2?family=Material+Symbols+Rounded:opsz,wght,FILL,GRAD@20..48,100..700,0..1,-50..200"
        />
        <link
          rel="stylesheet"
          href="https://cdn.jsdelivr.net/gh/fonts-archive/Paperlogy/Paperlogy.css"
          type="text/css"
        />
        <link
          href="https://cdn.jsdelivr.net/gh/sun-typeface/SUIT@2/fonts/variable/woff2/SUIT-Variable.css"
          rel="stylesheet"
        />
      </head>

      <body className="relative h-dvh w-full overflow-hidden">
        <OverlayProvider>
          <Provider>
            <Nav />
            <div className="relative container mx-auto flex h-full flex-col overflow-hidden">{children}</div>
          </Provider>
        </OverlayProvider>
      </body>
    </html>
  );
}
